name: CI

on:
    pull_request:
    push:
        branches:
            - main
        paths:
            - "src/**"
            - "*.json"
            - "*ignore"

jobs:
    build:
        name: "[Node ${{ matrix.node }} on ${{ matrix.os }}]: Run linter, Prettier, and build"

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ["14.x", "16.x"]
                os: [ubuntu-latest, windows-latest, macOS-latest]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}

            - name: Install dependencies
              run: npm ci

            - name: Run linter and Prettier
              run: npm run check

            - name: Build
              run: npm run build
